name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Move Package to Thunderstore dir
        run: mv obj/Debug/netstandard2.1/ReOpenShock.dll thunderstore/ReOpenShock.dll
      - name: Upload Thunderstore mod
        uses: actions/upload-artifact@v4
        with:
          name: Thunderstore Mod
          path: thunderstore