name: Publish

on:
  release:
    types: [created]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" thunderstore/manifest.json)" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat thunderstore/manifest.json )"
            echo "::error::Version in manifest.json does not match tag version"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Move Package to Thunderstore dir
        run: |
          mv obj/Debug/netstandard2.1/ReOpenShock.dll thunderstore/ReOpenShock.dll
          zip Thunderstore\ Mod.zip ./thunderstore/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thunderstore Mod
          path: thunderstore
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: lillithkt # the thunderstore 'team' to publish under
          description: Shocks you when you die!
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: ReOpenShock # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: repo
          repo: thunderstore.io
          path: thunderstore
          categories: | # <-- notice this pipe character
            clientside
            misc
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: "\nThis is published on [Thunderstore](https://thunderstore.io/c/repo/p/lillithkt/ReOpenShock/)"
          is_append_body: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.update_release.outputs.upload_url }}
          asset_path: ./Thunderstore\ Mod.zip
          asset_name: Thunderstore Mod.zip
          asset_content_type: application/octet-stream